### ISSUE TITLE
Market breaks when switching token in Add Liquidity tab

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/market#891]
**Describe the bug**
Go to add liquidity tab in asset actions, enter a token amount and switch from ocean token to the other data token and the market should break.

**Screenshots**
![Screenshot 2021-09-30 at 12 21 38](https://user-images.githubusercontent.com/37236152/135425979-2002d17f-e80f-43cb-872e-608c51d53643.png)
![Screenshot 2021-09-30 at 12 21 15](https://user-images.githubusercontent.com/37236152/135426019-0aefc3ea-918b-4b2e-b08a-4c3184405bad.png)

**Comment by kremalicious** [comment]
oh hey, found that too when crafting tweets :-) Fixed in #891 with this 2402ccf and I hope I didn't break anything else with that change

**Comment by KatunaNorbert** [comment]
Oh cool, I took a look over there and the market doesn't break anymore, but I stil get a lot of errors when wallet is not connected the asset network:
![Screenshot 2021-09-30 at 13.21.13.png](https://images.zenhubusercontent.com/5ff449b376fe2511ba59495d/f3d54fdf-f5e1-4c6e-af00-e0aab4d1eb03)


And still getting some error when connected to asset network:
![Screenshot 2021-09-30 at 13.20.31.png](https://images.zenhubusercontent.com/5ff449b376fe2511ba59495d/346f3f0d-b524-468f-96d2-719dd317078d)

**Comment by kremalicious** [comment]
Also found more weirdnesses but seems #891 still works as happy path with wallet connected gives errors in console but everything seems to work out, and lots of errors is on `main` too. Think we can release it and then investigate on this issue here to get all those errors out of console.

Another thing is that we should clear the input value when user switches tokens, as leaving the amount in there leads to unexpected UI things and the form validation then also gets confused

**Comment by KatunaNorbert** [comment]
Agree, we can merge the token approval PR, just wanted to point out the issues so we don't close this one too

**Comment by mihaisc** [comment]
>  E.g. easy fix could be to just disable input when !isAssetNetwork.

Totally agree with this. This is a behavior on other big dapps, if you are not on the proper network they don't let you do anything. And there is no point to do a big refactor at this time
